"use client"

import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { Card } from "@/components/ui/card"
import { useState } from "react"
import { ChevronDown } from "lucide-react"

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(0)

  const faqs = [
    {
      question: "What is Recreate AI?",
      answer:
        "Recreate AI is an AI-powered platform that transforms design screenshots and mockups into clean, production-ready code across multiple frameworks. It helps developers and teams build faster by automating the conversion process from design to code.",
    },
    {
      question: "Which frameworks are supported?",
      answer:
        "We support a wide range of modern frameworks including React, Next.js, Vue, Angular, Svelte, and more. You can choose your preferred framework when generating code, and our AI will optimize the output for that specific technology.",
    },
    {
      question: "How accurate is the code generation?",
      answer:
        "Our AI generates highly accurate, production-ready code that follows industry best practices. The code includes proper TypeScript types, accessibility features, responsive design, and is optimized for performance. You can also refine and customize the output to match your exact requirements.",
    },
    {
      question: "Can I use this for commercial projects?",
      answer:
        "Yes! All code generated by Recreate AI is yours to use in any project, including commercial applications. There are no royalties or licensing fees for the generated code.",
    },
    {
      question: "How does team collaboration work?",
      answer:
        "Team collaboration features allow you to share projects, components, and design systems with your team members. You can work together in real-time, maintain consistency across projects, and build a shared component library.",
    },
    {
      question: "What if I need help or support?",
      answer:
        "We offer community support for free users and priority email support for Pro users. Enterprise customers get dedicated account management and SLA-backed support. You can also access our comprehensive documentation and tutorials.",
    },
    {
      question: "Is there a free trial?",
      answer:
        "Yes! All paid plans come with a 14-day free trial. No credit card required to start. You can explore all features and decide which plan works best for you.",
    },
    {
      question: "How secure is my data?",
      answer:
        "We take security seriously. All data is encrypted in transit and at rest. We're SOC 2 compliant and follow industry best practices for data protection. Your designs and generated code are private and never used to train our models.",
    },
    {
      question: "Can I export my code?",
      answer:
        "Absolutely! You can export your generated code in various formats, download as ZIP files, or push directly to GitHub repositories. Pro and Enterprise users get additional export options and integrations.",
    },
    {
      question: "What happens if I cancel my subscription?",
      answer:
        "You can cancel anytime. Your account will remain active until the end of your billing period. You'll still have access to all your projects and can export your code. We also offer a data export option before cancellation.",
    },
  ]

  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex-1">
        <section className="container mx-auto px-4 pt-32 pb-20 md:pt-44 md:pb-32">
          <div className="mx-auto max-w-4xl text-center mb-16">
            <h1 className="mb-6 text-balance text-4xl font-bold leading-[1.1] tracking-tight md:text-5xl lg:text-6xl">
              Frequently Asked Questions
            </h1>
            <p className="mx-auto mb-8 max-w-2xl text-pretty text-lg leading-relaxed text-muted-foreground md:text-xl">
              Everything you need to know about Recreate AI. Can't find what you're looking for? Contact our support
              team.
            </p>
          </div>

          <div className="max-w-3xl mx-auto space-y-4">
            {faqs.map((faq, index) => (
              <Card key={index} className="border-border/50 overflow-hidden transition-all hover:border-accent/30">
                <button
                  onClick={() => setOpenIndex(openIndex === index ? null : index)}
                  className="w-full p-6 text-left flex items-center justify-between gap-4 hover:bg-accent/5 transition-colors"
                >
                  <h3 className="text-lg font-semibold pr-4">{faq.question}</h3>
                  <ChevronDown
                    className={`h-5 w-5 flex-shrink-0 transition-transform ${
                      openIndex === index ? "rotate-180" : ""
                    }`}
                  />
                </button>
                <div
                  className={`overflow-hidden transition-all ${
                    openIndex === index ? "max-h-96" : "max-h-0"
                  }`}
                >
                  <div className="px-6 pb-6 text-muted-foreground leading-relaxed">{faq.answer}</div>
                </div>
              </Card>
            ))}
          </div>
        </section>
      </main>
      <Footer />
    </div>
  )
}
